version: '3.8'

services:
  mcp-server:
    build: .
    container_name: py-ai-mcp
    env_file: .env
    ports:
      - "8001:8001"
    command: [ "python", "main.py", "mcp" ]
    networks:
      - py-ai

  ai-server:
    build: .
    container_name: py-ai-api
    env_file: .env
    environment:
      - MCP_WS_URL=http://mcp-server:8001/mcp
      - POSTGRESQL_URL=postgresql+psycopg://py-ai-ws:password@ai-db:5432/py-ai-ws
    ports:
      - "8000:8000"
    depends_on:
      - mcp-server
      - ai-db
    command: [ "python", "main.py", "api" ]
    networks:
      - py-ai

  ai-db:
    container_name: py-ai-postgresql
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=py-ai-ws
      - POSTGRES_DB=py-ai-ws
    volumes:
      - local-db:/var/lib/postgresql/data
    networks:
      - py-ai

  streamlit-app:
    build: .
    container_name: py-ai-streamlit
    ports:
      - "8501:8501"
    environment:
      # Pass the API URL as an environment variable
      - API_URL=http://ai-server:8000/chat/stream
    depends_on:
      - ai-server
    command: [
      "streamlit", "run", "src/streamlit_app/app.py",
      "--server.port", "8501",
      "--server.address", "0.0.0.0"
    ]
    networks:
      - py-ai

volumes:
  local-db:
    name: local-db

networks:
  py-ai:
    driver: bridge
