version: '3.8'

services:
  mcp-server:
    build: .
    container_name: py-ai-mcp
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - WEATHER_API_BASE_URL=${WEATHER_API_BASE_URL}
    ports:
      - "8001:8001"
    command: [ "python", "main.py", "mcp" ]

  api-server:
    build: .
    container_name: py-ai-api
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - MCP_WS_URL=http://mcp-server:8001/mcp
    ports:
      - "8000:8000"
    depends_on:
      - mcp-server
    command: [ "python", "main.py", "api" ]